from math import *

# Constants for the window display
WIDTH = 800
HEIGHT = WIDTH
FPS = 60
TILE_SIZE = 5
TITLE = "Programmer's Battlegrounds"

# Constants for map generation
ELEVATION_SEED = 574421234
RESOURCE_SEED = int(sqrt(abs(ELEVATION_SEED)) + pow(WIDTH, e))
MAP_SIZE = WIDTH / TILE_SIZE

# Elevation Constants
DEEP_LEVEL = 25
WATER_LEVEL = 100
BEACH_LEVEL = 120
PLAIN_LEVEL = 170
JUNGLE_LEVEL = 210
MOUNTAIN_LEVEL = 230
SNOW_LEVEL = 240
MAX_SCALE = 255
MIN_SCALE = 0
FREQUENCY = 10 / MAP_SIZE
POW_CONST = 1.0

# Island generation constants
MANHATTAN_DIST = int((2.5 * MAP_SIZE) / 4)
LAND_CONST = 0.15
WATER_CONST = 0.75
DROP_CONST = 3.0

# Game Constants
WATER_COOLDOWN = 2
DEEP_WATER_COOLDOWN = 5
BEACH_COOLDOWN = 0
PLAINS_COOLDOWN = 0
JUNGLE_COOLDOWN = 2
MOUNTAIN_COOLDOWN = 3
SNOW_COOLDOWN = 4
NUM_PLAYERS = 0
FOOD = 0
WATER = 1
WOOD = 2
STONE = 3
MIN_RESOURCE_LVL = 0
MAX_RESOURCE_LVL = 255
ELEVATION_MAP = 0
RESOURCE_MAP = 1
FOOD_MAP = 2
WATER_MAP = 3
WOOD_MAP = 4
STONE_MAP = 5
DAY_LENGTH = 180
ACTION_RATE = int(DAY_LENGTH / 180)
MID_DAY = DAY_LENGTH / 2
NIGHT = DAY_LENGTH
